# Generated by Django 2.1.3 on 2018-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181203_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, null=True, verbose_name='Task description'),
        ),
    ]
